version: "3.8"
services:

  compilar-q2-client:
    image: "gradle:jdk8-alpine"
    command: ["gradle", "clean", "build", "--no-daemon", "--info"]
    working_dir: /home/gradle/project
    # env_file: .env
    # environment:
    #     TOKEN: $TOKEN
    #     GHUSERNAME: $GHUSERNAME
    volumes:
        - gradle_cache:/home/gradle/.gradle
        - ./:/home/gradle/project
        
  ejecutar-q2-client:
    image: "gradle:jdk8-alpine"
    command: ["gradle", "clean", "run", "--no-daemon"]
    working_dir: /home/gradle/project
    # env_file: .env
    # environment:
    #     TOKEN: $TOKEN
    #     GHUSERNAME: $GHUSERNAME
    network_mode: host
    volumes:
        - gradle_cache:/home/gradle/.gradle
        - ./:/home/gradle/project
        
volumes:
    gradle_cache: